version: "3.7"

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"

  prisma:
    image: prisma/prisma:latest
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/my_database

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
